services:
  torchserve:
    build:
      context: .
      dockerfile: torchserve/Dockerfile
    networks:
      - ml-platform
    volumes:
      - model-store:/model-store
      - shared-config:/config
    ports:
      - "8080:8080"
      - "8082:8082"

  person-tracking:
    build:
      context: .
      dockerfile: services/person-tracking/Dockerfile
    networks:
      - ml-platform
    ports:
      - "8000:8000"
    depends_on:
      - torchserve

networks:
  ml-platform:
    driver: bridge

volumes:
  model-store:
  shared-config:
