services:
  torchserve:
    build:
      context: .
      dockerfile: torchserve/Dockerfile
    networks:
      - ml-platform
    volumes:
      - model-store:/model-store
      - shared-config:/config
    ports:
      - "8080:8080"
      - "8082:8082"

  person-tracking:
    build:
      context: .
      dockerfile: services/person-tracking/Dockerfile
    networks:
      - ml-platform
    ports:
      - "8000:8000"
    depends_on:
      - torchserve

  prometheus:
    image: prom/prometheus:latest
    networks:
      - ml-platform
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - torchserve
  grafana:
    image: grafana/grafana:latest
    networks:
      - ml-platform
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
networks:
  ml-platform:
    driver: bridge

volumes:
  model-store:
  shared-config:
  prometheus-data:
  grafana-data:
